function copyCalibration(info)

srcDir = fullfile(info.srcDir, 'fmap');

dstDir = fullfile( ...
    info.derivativesRoot, ...
    'calibration', ...
    info.sub, ...
    info.ses, ...
    'fmap');

ensureDirectory(dstDir);

copyIfPresent( ...
    fullfile(srcDir, 'sens.mat'), ...
    fullfile(dstDir, sprintf( ...
        '%s_%s_desc-bart_sensitivity.mat', ...
        info.sub, info.ses)));

copyIfPresent( ...
    fullfile(srcDir, 'sens.json'), ...
    fullfile(dstDir, sprintf( ...
        '%s_%s_desc-bart_sensitivity.json', ...
        info.sub, info.ses)));

end
